### ISSUE TITLE
`fetch_civet` missing from pypi release

### ISSUE THREAD

**Issue by ReinderVosDeWael** [netneurolab/netneurotools#108]
I was hoping to use the function `netneurotools.datasets.fetchers.fetch_civet`. However, it seems like this function hasn't made it into a released version yet. Are there any plans to push a new version to PyPi in the near future?

**Comment by rmarkello** [comment]
Hey @ReinderVosDeWael ! The inimitable @liuzhenqi77 just cut a release that should ship with the `fetch_civet()` functionality. Let us know if that works for you!

As a heads-up, we've been working on standardizing some of these atlases + fetchers (along with a variety of other hopefully-useful functionality) in the to-be-released [`neuromaps`](https://github.com/netneurolab/neuromaps) package. Once that's released it might be a better place to go for this (as it'll have a wider variety of the CIVET surfaces, and in different resolutions). (We're hoping to make an initial release in the next couple of weeks—just need to work out a few bugs and beef up documentation and whatnot.)

I'm closing this for now but feel free to ping if you have any other questions or issues with the new release.
