### ISSUE TITLE
Not compatible with `nilearn` version 0.10.1 onwards

### ISSUE THREAD

**Issue by ghisvail** [netneurolab/netneurotools#132]
There has been a significant [refactoring effort](https://github.com/nilearn/nilearn/pull/4086) on private utilities used throughout `nilearn`.

As a result, importing the `nilearn` file fetching utilities produces an `ImportError` when `netneurotools` is used alongside a recent enough version of `nilearn`. It should be easily fixable by some try / catch logic.

**Comment by liuzhenqi77** [comment]
Fixed in #130
