### ISSUE TITLE
Add `fetch_brain_annotations()` function

### ISSUE THREAD

**Issue by rmarkello** [netneurolab/netneurotools#88]
Discussed in a lab meeting, this might provide users with (surface-level?) data for a number of interesting brain attributes, including (but not limited to):

- Cortical thickness,
- T1w/T2w ratio,
- FC gradients (1 and 2?)
- PC1 (or something similar) of whole-brain gene expression,
- FC strength
- SC degree
- MEG power spectra maps
- hctsa gradients (Shafiei et al., 2020, biorxiv)

Users could then just parcellate the data (however they want) and be on their merry way. We'd need to make sure the data can be freely shared and whatnot (i.e., HCP data requires a registration so are not ideal for this...).

**Comment by rmarkello** [comment]
Thinking more about this recently, I think we're gonna go with the `fsaverage6` surface for now. (I personally prefer `fsaverage5`, but it seems like there exist a number of annotations in `fsaverage6` format already so we take the hand we're dealt.)

Another concern: a lot of the aforementioned annotations exist largely in _parcellated_ format (i.e., gene expression cannot exist in `fsaverage6` density—except via interpolation a la Gryglewski et al., 2018, NeuroImage, I suppose...). We will have to have a good think about the best way to get some of these annotations into `fsaverage6` space—or, I suppose, only provide them in parcellated form (??).

**Comment by liuzhenqi77** [comment]
Superseded by [neuromaps](https://github.com/netneurolab/neuromaps)!
