### ISSUE TITLE
Add dominance analysis function

### ISSUE THREAD

**Issue by liuzhenqi77** [netneurolab/netneurotools#96]
I have an example script [here](https://gist.github.com/liuzhenqi77/0087028a25c4f6d13d887e66894c3c0c) to get some dominance analysis stats. It's faster than the [original package](https://github.com/dominance-analysis/dominance-analysis), but can still be further optimized / parallelized. Since we are using it more, maybe we could discuss what extra features we need and integrate it into netneurotools.

**Comment by rmarkello** [comment]
Yes, definitely! This would be a perfect fit for `netneurotools.stats` I think :grin: The gist you've linked to would be great as a PR—no need to do any further optimizing for now. The only note I have right now is that we don't currently require `tqdm`, but it's such a lightweight dependency you're welcome to add it (or you can remove the calls from your function, if you'd prefer not to 🤷‍♂️).

Ping me once you've got a PR open and I'll do a quick pass!
